### ISSUE TITLE
IMPROVEMENT: Letter Capitalizing w/ Journals

### ISSUE THREAD

**Issue by RinVindor** [rlach/wiki-import#5]
So when you grab some of the pages they sometimes have lower case lettering in the wiki *but* the Foundry system auto capitalizes the first letter of Journals which means a number of links are broken due to this so it'd be awesome if the module just auto capitalized the first letter to prevent this issue.

**Comment by rlach** [comment]
I cannot really replicate it. I've tried on 0.8.8 and 0.9.0 and on both the journal entries are not automatically capitalized by foundry. I could for example make an article eBay and link to it would work.

<img width="1088" alt="Zrzut ekranu 2022-01-6 o 20 45 40" src="https://user-images.githubusercontent.com/5655000/148442075-d279cfe6-070f-46d1-a45f-05f46138dccf.png">
 
That said I'll be adding a setting "Auto-capitalize links" which will create links like `@JournalEntry[EBay]{eBay}` instead of `@JournalEntry[eBay]{eBay}`
